spring:
  profiles:
    active: develop
  batch:
    job:
      names: ${job.name:NONE}

#groupping
---
spring:
  profiles:
    group:
      develop :
        - devdb






---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver



---
spring:
  config:
    activate:
      on-profile: devdb
  main:
    allow-bean-definition-overriding: true
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/testdb?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      driver-class-name: org.mariadb.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true