spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver



---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/testdb?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      driver-class-name: org.mariadb.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
